/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Custom Lighthouse config consumers reference via .lighthouserc.js's `configPath`
 * setting (a first-class Lighthouse setting — see docs/configuration.md). Adds the
 * structured-data-json-ld, structured-data-schema-properties,
 * structured-data-rich-result-eligibility, structured-data-type-conflicts,
 * structured-data-deprecated-properties,
 * pixel-width-truncation, meta-description-identical-to-title, document-title-quality,
 * document-h1-count, h1-title-relevance, robots-directives-report, robots-directives-conflict,
 * canonical-https, favicon-presence, favicon-quality, manifest-icons,
 * open-graph-completeness, open-graph-canonical-match, open-graph-image-reachable,
 * twitter-card-completeness, social-preview-content, robots-txt-sitemap-declared,
 * robots-txt-crawler-access, robots-txt-rule-conflicts, sitemap-valid, sitemap-duplicate-urls,
 * sitemap-limits, sitemap-url-status, sitemap-robots-crossref, sitemap-indexability,
 * llms-txt-structure, mixed-content, hsts-quality, ssl-certificate-expiry, soft-not-found, url-variant-consistency, redirect-chain-length,
 * redirect-loop, indexability-verdict, indexability-conflicts, and crawl-coverage gatherers/audits on top
 * of Lighthouse's default set.
 *
 * Paths below are plain relative strings, not require.resolve() calls: this file is
 * ESM (no bare `require`), and Lighthouse's own module resolver
 * (core/config/config-helpers.js's resolveModulePath) already resolves relative paths
 * against this config file's own directory natively — no extra resolution needed.
 *
 * `extends: 'lighthouse:default'` is required — omitting it would replace Lighthouse's
 * entire default audit/category set instead of adding to it. See
 * test/lighthouse-config.test.js for the regression test that catches this if dropped.
 */

/** @type {import('lighthouse/types/config.js').default} */
const config = {
  extends: 'lighthouse:default',
  artifacts: [
    {id: 'StructuredDataJsonLd', gatherer: './gatherers/structured-data-json-ld.js'},
    {id: 'PixelWidth', gatherer: './gatherers/pixel-width.js'},
    {id: 'Headings', gatherer: './gatherers/headings.js'},
    {id: 'FaviconLinks', gatherer: './gatherers/favicon-links.js'},
    {id: 'SitemapDocuments', gatherer: './gatherers/sitemap-documents.js'},
    {id: 'LlmsTxt', gatherer: './gatherers/llms-txt.js'},
    {id: 'Soft404Probe', gatherer: './gatherers/soft-404-probe.js'},
    {id: 'ImageAltText', gatherer: './gatherers/image-alt-text.js'},
    {id: 'RenderedHtml', gatherer: './gatherers/rendered-html.js'},
    {id: 'DeviceFetches', gatherer: './gatherers/device-fetches.js'},
    {id: 'FieldData', gatherer: './gatherers/field-data.js'},
    {id: 'HreflangData', gatherer: './gatherers/hreflang-data.js'},
    {id: 'UrlVariants', gatherer: './gatherers/url-variants.js'},
    {id: 'IndexabilitySignals', gatherer: './gatherers/indexability-signals.js'},
    {id: 'SiteCrawl', gatherer: './gatherers/site-crawl.js'},
  ],
  audits: [
    './audits/structured-data-json-ld.js',
    './audits/structured-data-schema-properties.js',
    './audits/structured-data-rich-result-eligibility.js',
    './audits/structured-data-type-conflicts.js',
    './audits/structured-data-deprecated-properties.js',
    './audits/pixel-width-truncation.js',
    './audits/meta-description-identical-to-title.js',
    './audits/document-title-quality.js',
    './audits/document-h1-count.js',
    './audits/h1-title-relevance.js',
    './audits/robots-directives-report.js',
    './audits/robots-directives-conflict.js',
    './audits/canonical-https.js',
    './audits/favicon-presence.js',
    './audits/favicon-quality.js',
    './audits/manifest-icons.js',
    './audits/open-graph-completeness.js',
    './audits/open-graph-canonical-match.js',
    './audits/open-graph-image-reachable.js',
    './audits/twitter-card-completeness.js',
    './audits/social-preview-content.js',
    './audits/robots-txt-sitemap-declared.js',
    './audits/robots-txt-crawler-access.js',
    './audits/robots-txt-rule-conflicts.js',
    './audits/sitemap-valid.js',
    './audits/sitemap-duplicate-urls.js',
    './audits/sitemap-limits.js',
    './audits/sitemap-url-status.js',
    './audits/sitemap-robots-crossref.js',
    './audits/sitemap-indexability.js',
    './audits/llms-txt-structure.js',
    './audits/mixed-content.js',
    './audits/hsts-quality.js',
    './audits/ssl-certificate-expiry.js',
    './audits/soft-not-found.js',
    './audits/url-variant-consistency.js',
    './audits/redirect-chain-length.js',
    './audits/redirect-loop.js',
    './audits/indexability-verdict.js',
    './audits/indexability-conflicts.js',
    './audits/crawl-coverage.js',
    './audits/duplicate-titles.js',
    './audits/duplicate-descriptions.js',
    './audits/thin-content.js',
    './audits/canonical-conflicts.js',
    './audits/duplicate-content.js',
    './audits/dead-end-pages.js',
    './audits/internal-link-counts.js',
    './audits/orphan-pages.js',
    './audits/crawl-depth.js',
    './audits/broken-internal-links.js',
    './audits/redirecting-internal-links.js',
    './audits/internal-redirect-chains.js',
    './audits/anchor-text-diversity.js',
    './audits/descriptive-anchor-text.js',
    './audits/pagination-links.js',
    './audits/paginated-canonical.js',
    './audits/pagination-trap.js',
    './audits/broken-external-links.js',
    './audits/hreflang-codes.js',
    './audits/hreflang-return-links.js',
    './audits/hreflang-alternate-status.js',
    './audits/hreflang-canonical.js',
    './audits/hreflang-x-default.js',
    './audits/hreflang-sitemap-consistency.js',
    './audits/hreflang-locale-meta.js',
    './audits/core-web-vitals-field.js',
    './audits/render-blocking-report.js',
    './audits/request-weight-report.js',
    './audits/js-head-signals.js',
    './audits/js-internal-links.js',
    './audits/js-visible-content.js',
    './audits/raw-rendered-diff.js',
    './audits/rendering-mode.js',
    './audits/hydration-errors.js',
    './audits/device-content-parity.js',
    './audits/image-alt-quality.js',
    './audits/image-filename-quality.js',
    './audits/image-lazy-above-fold.js',
    './audits/image-dimensions-attributes.js',
    './audits/image-oversized.js',
    './audits/image-legacy-formats.js',
    './audits/broken-images.js',
    './audits/url-length.js',
    './audits/url-query-parameters.js',
    './audits/url-session-tracking.js',
    './audits/url-encoding.js',
    './audits/url-case-variants.js',
    './audits/url-trailing-slash-variants.js',
    './audits/url-normalization.js',
  ],
  categories: {
    'seo-extended': {
      title: 'Extended SEO (fork)',
      auditRefs: [
        {id: 'structured-data-json-ld', weight: 1},
        {id: 'structured-data-schema-properties', weight: 1},
        {id: 'structured-data-rich-result-eligibility', weight: 1},
        {id: 'structured-data-type-conflicts', weight: 1},
        {id: 'structured-data-deprecated-properties', weight: 1},
        {id: 'pixel-width-truncation', weight: 1},
        {id: 'meta-description-identical-to-title', weight: 1},
        {id: 'document-title-quality', weight: 1},
        {id: 'document-h1-count', weight: 1},
        {id: 'h1-title-relevance', weight: 1},
        {id: 'robots-directives-report', weight: 1},
        {id: 'robots-directives-conflict', weight: 1},
        {id: 'canonical-https', weight: 1},
        {id: 'favicon-presence', weight: 1},
        {id: 'favicon-quality', weight: 1},
        {id: 'manifest-icons', weight: 1},
        {id: 'open-graph-completeness', weight: 1},
        {id: 'open-graph-canonical-match', weight: 1},
        {id: 'open-graph-image-reachable', weight: 1},
        {id: 'twitter-card-completeness', weight: 1},
        {id: 'social-preview-content', weight: 1},
        {id: 'robots-txt-sitemap-declared', weight: 1},
        {id: 'robots-txt-crawler-access', weight: 1},
        {id: 'robots-txt-rule-conflicts', weight: 1},
        {id: 'sitemap-valid', weight: 1},
        {id: 'sitemap-duplicate-urls', weight: 1},
        {id: 'sitemap-limits', weight: 1},
        {id: 'sitemap-url-status', weight: 1},
        {id: 'sitemap-robots-crossref', weight: 1},
        {id: 'sitemap-indexability', weight: 1},
        {id: 'llms-txt-structure', weight: 1},
        {id: 'mixed-content', weight: 1},
        {id: 'hsts-quality', weight: 1},
        {id: 'ssl-certificate-expiry', weight: 1},
        {id: 'soft-not-found', weight: 1},
        {id: 'url-variant-consistency', weight: 1},
        {id: 'redirect-chain-length', weight: 1},
        {id: 'redirect-loop', weight: 1},
        {id: 'indexability-verdict', weight: 1},
        {id: 'indexability-conflicts', weight: 1},
        {id: 'crawl-coverage', weight: 1},
        {id: 'duplicate-titles', weight: 1},
        {id: 'duplicate-descriptions', weight: 1},
        {id: 'thin-content', weight: 1},
        {id: 'canonical-conflicts', weight: 1},
        {id: 'duplicate-content', weight: 1},
        {id: 'dead-end-pages', weight: 1},
        {id: 'internal-link-counts', weight: 1},
        {id: 'orphan-pages', weight: 1},
        {id: 'crawl-depth', weight: 1},
        {id: 'broken-internal-links', weight: 1},
        {id: 'redirecting-internal-links', weight: 1},
        {id: 'internal-redirect-chains', weight: 1},
        {id: 'anchor-text-diversity', weight: 1},
        {id: 'descriptive-anchor-text', weight: 1},
        {id: 'pagination-links', weight: 1},
        {id: 'paginated-canonical', weight: 1},
        {id: 'pagination-trap', weight: 1},
        {id: 'broken-external-links', weight: 1},
        {id: 'hreflang-codes', weight: 1},
        {id: 'hreflang-return-links', weight: 1},
        {id: 'hreflang-alternate-status', weight: 1},
        {id: 'hreflang-canonical', weight: 1},
        {id: 'hreflang-x-default', weight: 1},
        {id: 'hreflang-sitemap-consistency', weight: 1},
        {id: 'hreflang-locale-meta', weight: 1},
        {id: 'core-web-vitals-field', weight: 1},
        {id: 'render-blocking-report', weight: 1},
        {id: 'request-weight-report', weight: 1},
        {id: 'js-head-signals', weight: 1},
        {id: 'js-internal-links', weight: 1},
        {id: 'js-visible-content', weight: 1},
        {id: 'raw-rendered-diff', weight: 1},
        {id: 'rendering-mode', weight: 1},
        {id: 'hydration-errors', weight: 1},
        {id: 'device-content-parity', weight: 1},
        {id: 'image-alt-quality', weight: 1},
        {id: 'image-filename-quality', weight: 1},
        {id: 'image-lazy-above-fold', weight: 1},
        {id: 'image-dimensions-attributes', weight: 1},
        {id: 'image-oversized', weight: 1},
        {id: 'image-legacy-formats', weight: 1},
        {id: 'broken-images', weight: 1},
        {id: 'url-length', weight: 1},
        {id: 'url-query-parameters', weight: 1},
        {id: 'url-session-tracking', weight: 1},
        {id: 'url-encoding', weight: 1},
        {id: 'url-case-variants', weight: 1},
        {id: 'url-trailing-slash-variants', weight: 1},
        {id: 'url-normalization', weight: 1},
      ],
    },
  },
};

export default config;
